BASE_URL = "https://e621.net"
POSTS_URL = BASE_URL + "/posts.json"
UPLOAD_URL = BASE_URL + "/uploads.json"
FLAGS_URL = BASE_URL + "/post_flags.json"
NOTES_URL = BASE_URL + "/notes.json"
POOLS_URL = BASE_URL + "/pools.json"
FAVORITES_URL = BASE_URL + "/favorites.json"
SETS_URL = BASE_URL + "/post_sets.json"

POST_URL = BASE_URL + "/posts/"
NOTE_URL = BASE_URL + "/notes/"
POOL_URL = BASE_URL + "/pools/"
FAVORITE_URL = BASE_URL = "/favorites/"
SET_URL = BASE_URL + "/post_sets/"
